In [47]:
!git clone https://github.com/Atcold/PyTorch-Deep-Learning-Minicourse

Cloning into 'PyTorch-Deep-Learning-Minicourse'...
remote: Counting objects: 297, done.
remote: Compressing objects: 100% (80/80), done.
remote: Total 297 (delta 51), reused 49 (delta 17), pack-reused 200
Receiving objects: 100% (297/297), 12.69 MiB | 37.77 MiB/s, done.
Resolving deltas: 100% (152/152), done.


In [1]:
!pip3 install http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp36-cp36m-linux_x86_64.whl 

    100% |████████████████████████████████| 592.3MB 1.0MB/s 


In [2]:
!pip3 install torchvision

    100% |████████████████████████████████| 61kB 3.8MB/s 
    100% |████████████████████████████████| 2.0MB 10.2MB/s 
  Found existing installation: Pillow 4.0.0
    Uninstalling Pillow-4.0.0:
      Successfully uninstalled Pillow-4.0.0


In [0]:
import torch

In [0]:
torch.sq

In [0]:
torch.*Tensor?


In [0]:
torch.nn.Module()

In [0]:
torch.nn.Module?

In [0]:
torch.nn.Module??

In [6]:
t = torch.Tensor(2,3,4)
type(t)

torch.FloatTensor

In [12]:
t.size()

torch.Size([2, 3, 4])

In [11]:
t.shape

torch.Size([2, 3, 4])

In [7]:
# t.size() is a classic tuple =>
print('t size:', ' \u00D7 '.join(map(str, t.size())))

t size: 2 × 3 × 4


In [8]:
print(f'point in a {t.numel()} dimensional space')
print(f'organised in {t.dim()} sub-dimensions')

point in a 24 dimensional space
organised in 3 sub-dimensions


In [9]:
t


(0 ,.,.) = 
1.00000e-36 *
   1.1910  0.0000  0.0000  0.0000
   0.0000  0.0000  0.0000  0.0000
   0.0000  0.0000  0.0000  0.0000

(1 ,.,.) = 
1.00000e-36 *
   0.0000  0.0000  0.0000  0.0000
   0.0000  0.0000  0.0000  0.0000
   0.0000  0.0000  0.0000  0.0000
[torch.FloatTensor of size 2x3x4]

In [10]:
t.random_(10)


(0 ,.,.) = 
  7  0  7  8
  9  2  6  0
  1  8  8  7

(1 ,.,.) = 
  1  9  0  0
  3  7  5  7
  9  7  9  1
[torch.FloatTensor of size 2x3x4]

In [11]:
t


(0 ,.,.) = 
  7  0  7  8
  9  2  6  0
  1  8  8  7

(1 ,.,.) = 
  1  9  0  0
  3  7  5  7
  9  7  9  1
[torch.FloatTensor of size 2x3x4]

In [13]:
r = torch.Tensor(t)
r.resize_(3,8)
r


    7     0     7     8     9     2     6     0
    1     8     8     7     1     9     0     0
    3     7     5     7     9     7     9     1
[torch.FloatTensor of size 3x8]

In [14]:
r.zero_()


    0     0     0     0     0     0     0     0
    0     0     0     0     0     0     0     0
    0     0     0     0     0     0     0     0
[torch.FloatTensor of size 3x8]

In [15]:
t


(0 ,.,.) = 
  0  0  0  0
  0  0  0  0
  0  0  0  0

(1 ,.,.) = 
  0  0  0  0
  0  0  0  0
  0  0  0  0
[torch.FloatTensor of size 2x3x4]

In [0]:
s=r.clone()

In [18]:
s


    0     0     0     0     0     0     0     0
    0     0     0     0     0     0     0     0
    0     0     0     0     0     0     0     0
[torch.FloatTensor of size 3x8]

In [19]:
s.fill_(1)


    1     1     1     1     1     1     1     1
    1     1     1     1     1     1     1     1
    1     1     1     1     1     1     1     1
[torch.FloatTensor of size 3x8]

In [20]:
r


    0     0     0     0     0     0     0     0
    0     0     0     0     0     0     0     0
    0     0     0     0     0     0     0     0
[torch.FloatTensor of size 3x8]

In [5]:
v = torch.Tensor([1,2,3,4]);
v


 1
 2
 3
 4
[torch.FloatTensor of size 4]

In [6]:

print(f'dim: {v.dim()}, size: {v.size()[0]}')

dim: 1, size: 4


In [7]:
w = torch.Tensor([1, 0, 2, 0]); 
w


 1
 0
 2
 0
[torch.FloatTensor of size 4]

In [8]:
# Element-wise multiplication
v * w


 1
 0
 6
 0
[torch.FloatTensor of size 4]

In [9]:
v @ w

7.0

In [10]:
x = torch.Tensor(5).random_(10); 
x


 1
 4
 5
 9
 4
[torch.FloatTensor of size 5]

In [11]:
print(f'first: {x[0]}, last: {x[-1]}')

first: 1.0, last: 4.0


In [12]:
# Extract sub-Tensor [from:to)
x[1:2 + 1]


 4
 5
[torch.FloatTensor of size 2]

In [13]:
# Extract sub-Tensor [from:to)
x[1:2 ]


 4
[torch.FloatTensor of size 1]

In [14]:
v


 1
 2
 3
 4
[torch.FloatTensor of size 4]

In [15]:
v = torch.arange(1, 4 + 1); 
v


 1
 2
 3
 4
[torch.FloatTensor of size 4]

In [16]:
print(v.pow(2), v)


  1
  4
  9
 16
[torch.FloatTensor of size 4]
 
 1
 2
 3
 4
[torch.FloatTensor of size 4]



In [17]:
print(v.pow_(2), v)


  1
  4
  9
 16
[torch.FloatTensor of size 4]
 
  1
  4
  9
 16
[torch.FloatTensor of size 4]



In [18]:
m = torch.Tensor([[2, 5, 3, 7],
                  [4, 2, 1, 9]]); m


 2  5  3  7
 4  2  1  9
[torch.FloatTensor of size 2x4]

In [19]:
m.dim()

2

In [20]:
print(m.size(0), m.size(1), m.size(), sep=' -- ')

2 -- 4 -- torch.Size([2, 4])


In [21]:

m.numel()

8

In [22]:
m[0][2]

3.0

In [23]:
m[0, 2]

3.0

In [24]:
m[:, 1]


 5
 2
[torch.FloatTensor of size 2]

In [25]:
m[:, [1]]


 5
 2
[torch.FloatTensor of size 2x1]

In [29]:
m[[0], :]


 2  5  3  7
[torch.FloatTensor of size 1x4]

In [30]:
m[0, :]


 2
 5
 3
 7
[torch.FloatTensor of size 4]

In [28]:
v = torch.arange(1, 4 + 1); v


 1
 2
 3
 4
[torch.FloatTensor of size 4]

In [31]:
m @ v


 49
 47
[torch.FloatTensor of size 2]

In [32]:
m[[0], :] @ v


 49
[torch.FloatTensor of size 1]

In [33]:
m[[1], :] @ v


 47
[torch.FloatTensor of size 1]

In [34]:
m + torch.rand(2, 4)


 2.5330  5.7922  3.8856  7.7260
 4.5892  2.8326  1.6566  9.1414
[torch.FloatTensor of size 2x4]

In [35]:
m - torch.rand(2, 4)


 1.4382  4.9164  2.4154  6.3458
 3.7295  1.0786  0.5381  8.5224
[torch.FloatTensor of size 2x4]

In [36]:
m * torch.rand(2, 4)


 1.3694  1.6451  0.1283  6.7053
 1.9705  1.0682  0.0382  6.3417
[torch.FloatTensor of size 2x4]

In [37]:
m / torch.rand(2, 4)


 28.4349  14.3284  13.0601  16.2171
  4.6658   3.5168   2.2047  40.9038
[torch.FloatTensor of size 2x4]

In [38]:
m.t()


 2  4
 5  2
 3  1
 7  9
[torch.FloatTensor of size 4x2]

In [39]:
# Same as
m.transpose(0, 1)


 2  4
 5  2
 3  1
 7  9
[torch.FloatTensor of size 4x2]

In [40]:

torch.arange(3, 8 + 1)



 3
 4
 5
 6
 7
 8
[torch.FloatTensor of size 6]

In [41]:

torch.arange(5.7, -3, -2.1)


 5.7000
 3.6000
 1.5000
-0.6000
-2.7000
[torch.FloatTensor of size 5]

In [42]:

torch.linspace(3, 8, 20).view(1, -1)



Columns 0 to 9 
 3.0000  3.2632  3.5263  3.7895  4.0526  4.3158  4.5789  4.8421  5.1053  5.3684

Columns 10 to 19 
 5.6316  5.8947  6.1579  6.4211  6.6842  6.9474  7.2105  7.4737  7.7368  8.0000
[torch.FloatTensor of size 1x20]

In [43]:
torch.zeros(3, 5)


 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
[torch.FloatTensor of size 3x5]

In [44]:
torch.ones(3, 2, 5)


(0 ,.,.) = 
  1  1  1  1  1
  1  1  1  1  1

(1 ,.,.) = 
  1  1  1  1  1
  1  1  1  1  1

(2 ,.,.) = 
  1  1  1  1  1
  1  1  1  1  1
[torch.FloatTensor of size 3x2x5]

In [45]:
torch.eye(3)


 1  0  0
 0  1  0
 0  0  1
[torch.FloatTensor of size 3x3]

In [48]:

# Pretty plotting config
%run plot_conf.py

ERROR:root:File `'plot_conf.py'` not found.


In [49]:

plt_style()

NameError: ignored

In [0]:
torch.*Tensor?

In [51]:
m


 2  5  3  7
 4  2  1  9
[torch.FloatTensor of size 2x4]

In [52]:

m.double()


 2  5  3  7
 4  2  1  9
[torch.DoubleTensor of size 2x4]

In [53]:
m.byte()


 2  5  3  7
 4  2  1  9
[torch.ByteTensor of size 2x4]

In [54]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
m.to(device)

AttributeError: ignored

In [55]:
m_np = m.numpy(); m_np

array([[2., 5., 3., 7.],
       [4., 2., 1., 9.]], dtype=float32)

In [56]:
m_np[0, 0] = -1; m_np

array([[-1.,  5.,  3.,  7.],
       [ 4.,  2.,  1.,  9.]], dtype=float32)

In [57]:
m


-1  5  3  7
 4  2  1  9
[torch.FloatTensor of size 2x4]

In [0]:
import numpy as np

In [60]:
n_np = np.arange(5)
n = torch.from_numpy(n_np)
print(n_np, n)

[0 1 2 3 4] 
 0
 1
 2
 3
 4
[torch.LongTensor of size 5]



In [61]:
a = torch.Tensor([[1, 2, 3, 4]])
b = torch.Tensor([[5, 6, 7, 8]])
print(a, b)


 1  2  3  4
[torch.FloatTensor of size 1x4]
 
 5  6  7  8
[torch.FloatTensor of size 1x4]



In [62]:

torch.cat((a, b), 0)


 1  2  3  4
 5  6  7  8
[torch.FloatTensor of size 2x4]

In [0]:

torch.cat((a, b), 1)